Document: u-boot-cubox-i
Title: Debian u-boot-cubox-i Manual
Author: <insert document author here>
Abstract: This manual describes what u-boot-cubox-i is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/u-boot-cubox-i/u-boot-cubox-i.sgml.gz

Format: postscript
Files: /usr/share/doc/u-boot-cubox-i/u-boot-cubox-i.ps.gz

Format: text
Files: /usr/share/doc/u-boot-cubox-i/u-boot-cubox-i.text.gz

Format: HTML
Index: /usr/share/doc/u-boot-cubox-i/html/index.html
Files: /usr/share/doc/u-boot-cubox-i/html/*.html
