Document: u-boot-cuboxi
Title: Debian u-boot-cuboxi Manual
Author: <insert document author here>
Abstract: This manual describes what u-boot-cuboxi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/u-boot-cuboxi/u-boot-cuboxi.sgml.gz

Format: postscript
Files: /usr/share/doc/u-boot-cuboxi/u-boot-cuboxi.ps.gz

Format: text
Files: /usr/share/doc/u-boot-cuboxi/u-boot-cuboxi.text.gz

Format: HTML
Index: /usr/share/doc/u-boot-cuboxi/html/index.html
Files: /usr/share/doc/u-boot-cuboxi/html/*.html
